name: Build
on:
  push:

env:
  DOCKER_BUILDKIT: 1

permissions:
  contents: read
  packages: write

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3.8

      - name: Generate Matrix
        id: generate-matrix
        run: |
          MATRIX=$(nu matrix.nu)
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$MATRIX" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  build:
      name: ${{ matrix.shopwareVersion }}
      runs-on: ubuntu-latest
      needs: [generate-matrix]
      strategy: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - uses: docker/build-push-action@v5
          with:
            tags: ghcr.io/friendsofshopware/shopware-demo-environment:${{ matrix.shopwareVersion }}
            cache-from: type=gha,scope=${{ matrix.shopwareVersion }}
            cache-to: type=gha,mode=max,scope=${{ matrix.shopwareVersion }}
            platforms: linux/amd64
            build-args: |
              PHP_VERSION=${{ matrix.phpVersion }}
              SHOPWARE_VERSION=${{ matrix.shopwareVersion }}
            push: true
            provenance: true
